% Generated on Tue Jul  9 14:24:53 2019

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {9}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Resource Utilization Table for worker "complex\_mixer"}\\
        \hline
        \rowcolor{blue}
            Configuration & OCPI Target & Tool   & Version & Device          & Registers (Typ) & LUTs (Typ) & Fmax (MHz) (Typ) & Memory/Special Functions \\
            \hline
            0             & zynq        & Vivado & 2017.1  & xc7z020clg400-3 & 558             & 379        & N/A              & \begin{tabular}{@{}l@{}}RAMB36E1: 7 \\ DSP48E1: 3 \\ BUFG: 2 \\ RAMB18E1: 1 \\ BUFGCTRL: 2\end{tabular} \\
            \hline
        \end{longtable}
\end{tiny}
